config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root "events#index"

  resources :events
  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  validates :user, presence: true

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events

  validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  private

  def set_name
    self.name = "Товарищ №#{rand(777)}" if self.name.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_user_can_edit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update,
      keys: [:password, :password_confirmation, :current_password]
    )
  end

  def current_user_can_edit?(event)
    user_signed_in? && event.user == current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

    def set_current_user_event
      @event = current_user.events.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :address, :datetime, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

    def set_current_user
      @user = current_user
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    # TODO: user real avatars
    asset_path('user.png')
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= content_tag 'div', '',
                        class: 'event-background',
                        style: "background-image: url(#{asset_path('event_thumb.jpg')})"
        %>
        <div class="thumbnail-inner event-info-inner">
            <div class="caption">
                <div class="event-description">
                  <h3><%= link_to event.title, event_path(event) %></h3>
                  <h3>
                    <small><%= l event.datetime, format: :long %></small>
                  </h3>
                  <div class="buffer-both"><%= event.address %></div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :datetime %>
      <%= f.datetime_select :datetime, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>

<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">

  <div class="event-info row">

    <div class="col-md-12">
      <%= content_tag 'div', '',
                      class: 'event-background',
                      style: "background-image: url(#{asset_path('event.jpg')})"
      %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :long %></h3>
            <h3>
              <small>
                <%= link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}" %>
              </small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-top">
              <%= link_to 'Изменить', edit_event_path(@event), class: 'btn btn-primary' %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bbq" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to 'Профиль', current_user %></li>
                <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to 'Войти', new_user_session_path %></li>
                <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">

        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; <%= t('app.company') %> 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>

<% if errors.any? %>
    <div class="alert alert-danger">
      <div class="lead buffer-bottom">
        В вашей форме <%= errors.count %> <%= Russian.p(errors.count, "ошибка", "ошибки", "ошибок") %>
      </div>

      <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>
  </div>

   <div class="form-group">
     <%= f.label :email %>
     <%= f.text_field :email, class: 'form-control' %>
   </div>

   <div class="actions">
     <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
   </div>

<% end %>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>

    <p class="buffer-top">
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>

  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top">
      <%= link_to "Редактировать профиль", edit_user_path(@user), class: 'btn btn-default' %>
    </p>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
          <h3>Организовал:</h3>
          <div class="row">
            <%= render partial: 'events/event', collection: @user.events %>
          </div>
      <% else %>
          <p class="buffer-top">Пользователь пока не организовал ни одного события</p>
      <% end %>
    </div>
  </div>
</div>